export PS1='%~ $ '
export USER='jnandzik'
export MAIL='jnandzik@student.42warsaw.pl'
export USER42='jnandzik'
export MAIL42='jnandzik@student.42warsaw.pl'
alias mini='~/mini-moulinette/mini-moul.sh'
alias sync_ltg="rsync -av --progress ~/git/C_Piscine/ ~/git/.C_Piscine_gh/ --exclude .git"
alias sync_gtl="rsync -av --progress ~/git/.C_Piscine_gh/ ~/git/C_Piscine/ --exclude .git"
alias com="gcc -o code.out"
alias comf="gcc -Wall -Werror -Wextra -o code.out"
alias coma="cc -o code.out *.c"
alias comfa="cc -Wall -Werror -Wextra -o code.out *.c"
